<li>
            <div class="img">
              <a href="[field:arcurl/]"><img src="[field:litpic/]"/></a>
            </div>
            <div class="info">
              <h3><a href="">[field:fulltitle/]</a></h3>
              <p>[field:infos/]</p>
              <a class="readall btn" href="[field:arcurl/]">阅读全文</a>
              <a class="btn" href="javascript:onKST();">在线咨询</a>
            </div>
          </li>