<li>
            <div class="img">
              <a href="[field:arcurl/]"><img src="[field:litpic/]"/></a>
            </div>
            <div class="info">
              <h3><a href="[field:arcurl/]">[field:title/]<span>[field:shorttitle/]</span></a></h3>
              <p><b>简介：</b>[field:infos/]……<a href="[field:arcurl/]">[详情]</a></p>
              <a class="zixun btn" href="javascript:onKST();">在线咨询</a>
              <a class="guahao btn" href="javascript:show_order();">直接挂号</a>
            </div>
          </li>