<?php
$z[0]=Array("field","",395,417);
$z[0][4]['name']="typename";
$z[1]=Array("global","",420,446);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",490,512);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",554,579);
$z[3][4]['name']="description";
$z[4]=Array("global","",632,664);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",731,763);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("include","",832,869);
$z[6][4]['filename']="header.htm";
$z[7]=Array("include","",876,913);
$z[7][4]['filename']="banner.htm";
$z[8]=Array("field","\n        \$a=mb_strlen(@me);\n        @me=cn_substr(@me,\$a-4);\n        ",955,1078);
$z[8][4]['name']="position";
$z[8][4]['runphp']="yes";
$z[9]=Array("list","\n          <li>\n            <h3><a href=\"[field:arcurl/]\">[field:title/]</a></h3>\n            <p>[field:infos/]……<a href=\"[field:arcurl/]\">[阅读全文]</a></p>\n          </li>\n          ",1151,1393);
$z[9][4]['pagesize']="8";
$z[9][4]['infolen']="100";
$z[10]=Array("pagelist","",1481,1547);
$z[10][4]['listitem']="index,end,pre,next,pageno";
$z[10][4]['listsize']="1";
$z[11]=Array("global","",1731,1763);
$z[11][4]['name']="cfg_templets_skin";
$z[12]=Array("global","",2172,2204);
$z[12][4]['name']="cfg_templets_skin";
$z[13]=Array("include","",3027,3070);
$z[13][4]['filename']="common_order.htm";
$z[14]=Array("include","",3077,3114);
$z[14][4]['filename']="footer.htm";

?>