<?php
$z[0]=Array("field","",395,417);
$z[0][4]['name']="typename";
$z[1]=Array("global","",420,446);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",490,512);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",554,579);
$z[3][4]['name']="description";
$z[4]=Array("global","",632,664);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",731,763);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("include","",1274,1311);
$z[6][4]['filename']="header.htm";
$z[7]=Array("include","",1318,1355);
$z[7][4]['filename']="banner.htm";
$z[8]=Array("field","\n        \$a=mb_strlen(@me);\n        @me=cn_substr(@me,\$a-4);\n        ",1397,1520);
$z[8][4]['name']="position";
$z[8][4]['runphp']="yes";
$z[9]=Array("channelartlist","\n          <li>\n            <div class=\"t1\"><a href=\"{dede:field.typeurl/}\">{dede:field.typename/}</a></div>\n            <div class=\"t2\">\n            {dede:channel type=\"son\"}\n            <a href=\"[field:typeurl/]\">[field:typename/]</a>\n            {/dede:channel}\n            </div>\n          </li>\n          ",1593,1986);
$z[9][4]['typeid']="1,543,427,23,27,564,16,4,5,541";
$z[10]=Array("include","",2024,2061);
$z[10][4]['filename']="footer.htm";

?>